# Generated by Django 3.2.5 on 2021-07-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_code',
            field=models.CharField(default='NULL', max_length=15),
        ),
    ]
