# Generated by Django 3.2.5 on 2021-07-26 21:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cbtuser', '0002_alter_cbtuser_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=500)),
                ('description', models.TextField(max_length=1500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cbtuser.cbtuser')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
