# Generated by Django 3.2.5 on 2021-07-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbtuser',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
